INSERT INTO hobbies(nombre)
VALUES("Leer"),
VALUES("Deportes/Ejercicio"),
VALUES("Videojuegos"),
VALUES("Fotografía"),
VALUES("Dormir"),
VALUES("Cocinar"),
VALUES("Comer"),
VALUES("Música"),
VALUES("Ver series o películas"),
VALUES("Acampar"),
VALUES("Viajar"),
VALUES("Ir al cine"),
VALUES("Programar"),
VALUES("Ir de compras"),
VALUES("Dibujar"),
VALUES("Anime"),
VALUES("Juegos de cartas"),
VALUES("Juegos de mesa"),
VALUES("Hacer cortometrajes"),
VALUES("Carreras a alta velocidad");

INSERT INTO videojuegos(nombre, crossplay, activado)
VALUES("Fortnite", 1, 1),
VALUES("Warzone", 1, 1),
VALUES("Call of Duty", 1, 1),
VALUES("League of Legends", 0, 1),
VALUES("Fall Guys", 1, 1),
VALUES("Among Us", 1, 1),
VALUES("Genshin Impact", 1, 1),
VALUES("FIFA", 1, 1),
VALUES("Age of Empires", 0, 1),
VALUES("Paladins", 1, 1),
VALUES("Rainbow Six", 1, 1),
VALUES("GTA V", 1, 1),
VALUES("Minecraft", 1, 1),
VALUES("Apex Legends", 1, 1),
VALUES("War Thunder", 1, 1),
VALUES("Fallout 76", 1, 1),
VALUES("Path of Exile", 0, 1),
VALUES("Counter Strike", 0, 1),
VALUES("Team Fortress", 0, 1),
VALUES("Halo", 1, 1),
VALUES("Overwatch", 1, 1),
VALUES("Rust", 1, 1),
VALUES("Ark", 1, 1),
VALUES("Valorant", 1, 1),
VALUES("Rocket League", 1, 1),
VALUES("F1", 1, 1),
VALUES("UFC", 1, 1),
VALUES("Clash Royale", 1, 1),
VALUES("Dragon Ball Xenoverse", 1, 1);

INSERT INTO plataformas(nombre)
VALUES("Xbox"),
VALUES("Playstation"),
VALUES("Switch"),
VALUES("PC"),
VALUES("Celular");

INSERT INTO usuarios(usuario, correo, nombre, contrasena, descripcion, discord)
VALUES('aetherjack115','aetherjack115@gmail.com','Anónimo','$2y$10$aSYXF8U8K23gtLqtesHKwOzQB72yv58RJhZ02ApwtXgN3FAG2YlAO','Hola a todos! Me registré en la encuesta!','aetherjack115'),
VALUES('elmike712','elmike712@gmail.com','Anónimo','$2y$10$aSYXF8U8K23gtLqtesHKwOzQB72yv58RJhZ02ApwtXgN3FAG2YlAO','Hola a todos! Me registré en la encuesta!','elmike712'),
VALUES('oryxthemadgod','oryxthemadgod@gmail.com','Anónimo','$2y$10$aSYXF8U8K23gtLqtesHKwOzQB72yv58RJhZ02ApwtXgN3FAG2YlAO','Hola a todos! Me registré en la encuesta!','oryxthemadgod'),
VALUES('gervinky','gervinky@gmail.com','Anónimo','$2y$10$aSYXF8U8K23gtLqtesHKwOzQB72yv58RJhZ02ApwtXgN3FAG2YlAO','Hola a todos! Me registré en la encuesta!','gervinky'),
VALUES('_anra_','_anra_@gmail.com','Anónimo','$2y$10$aSYXF8U8K23gtLqtesHKwOzQB72yv58RJhZ02ApwtXgN3FAG2YlAO','Hola a todos! Me registré en la encuesta!','_anra_'),
VALUES('altairrb','altairrb@gmail.com','Anónimo','$2y$10$aSYXF8U8K23gtLqtesHKwOzQB72yv58RJhZ02ApwtXgN3FAG2YlAO','Hola a todos! Me registré en la encuesta!','altairrb'),
VALUES('mendozazaurio','mendozazaurio@gmail.com','Anónimo','$2y$10$aSYXF8U8K23gtLqtesHKwOzQB72yv58RJhZ02ApwtXgN3FAG2YlAO','Hola a todos! Me registré en la encuesta!','mendozazaurio'),
VALUES('thankfulthrower','thankfulthrower@gmail.com','Anónimo','$2y$10$aSYXF8U8K23gtLqtesHKwOzQB72yv58RJhZ02ApwtXgN3FAG2YlAO','Hola a todos! Me registré en la encuesta!','thankfulthrower'),
VALUES('sylingbulker','sylingbulker@gmail.com','Anónimo','$2y$10$aSYXF8U8K23gtLqtesHKwOzQB72yv58RJhZ02ApwtXgN3FAG2YlAO','Hola a todos! Me registré en la encuesta!','sylingbulker'),
VALUES('fercats99','fercats99@gmail.com','Anónimo','$2y$10$aSYXF8U8K23gtLqtesHKwOzQB72yv58RJhZ02ApwtXgN3FAG2YlAO','Hola a todos! Me registré en la encuesta!','fercats99'),
VALUES('axelelrojo','axelelrojo@gmail.com','Anónimo','$2y$10$aSYXF8U8K23gtLqtesHKwOzQB72yv58RJhZ02ApwtXgN3FAG2YlAO','Hola a todos! Me registré en la encuesta!','axelelrojo'),
VALUES('el juan','el juan@gmail.com','Anónimo','$2y$10$aSYXF8U8K23gtLqtesHKwOzQB72yv58RJhZ02ApwtXgN3FAG2YlAO','Hola a todos! Me registré en la encuesta!','el juan'),
VALUES('deadslayer','deadslayer@gmail.com','Anónimo','$2y$10$aSYXF8U8K23gtLqtesHKwOzQB72yv58RJhZ02ApwtXgN3FAG2YlAO','Hola a todos! Me registré en la encuesta!','deadslayer'),
VALUES('juanm17','juanm17@gmail.com','Anónimo','$2y$10$aSYXF8U8K23gtLqtesHKwOzQB72yv58RJhZ02ApwtXgN3FAG2YlAO','Hola a todos! Me registré en la encuesta!','juanm17'),
VALUES('alejaelric','alejaelric@gmail.com','Anónimo','$2y$10$aSYXF8U8K23gtLqtesHKwOzQB72yv58RJhZ02ApwtXgN3FAG2YlAO','Hola a todos! Me registré en la encuesta!','alejaelric'),
VALUES('ninguno','ninguno@gmail.com','Anónimo','$2y$10$aSYXF8U8K23gtLqtesHKwOzQB72yv58RJhZ02ApwtXgN3FAG2YlAO','Hola a todos! Me registré en la encuesta!','ninguno'),
VALUES('pinchejaciel','pinchejaciel@gmail.com','Anónimo','$2y$10$aSYXF8U8K23gtLqtesHKwOzQB72yv58RJhZ02ApwtXgN3FAG2YlAO','Hola a todos! Me registré en la encuesta!','pinchejaciel'),
VALUES('flowercf','flowercf@gmail.com','Anónimo','$2y$10$aSYXF8U8K23gtLqtesHKwOzQB72yv58RJhZ02ApwtXgN3FAG2YlAO','Hola a todos! Me registré en la encuesta!','flowercf'),
VALUES('alsse','alsse@gmail.com','Anónimo','$2y$10$aSYXF8U8K23gtLqtesHKwOzQB72yv58RJhZ02ApwtXgN3FAG2YlAO','Hola a todos! Me registré en la encuesta!','alsse'),
VALUES('rata','rata@gmail.com','Anónimo','$2y$10$aSYXF8U8K23gtLqtesHKwOzQB72yv58RJhZ02ApwtXgN3FAG2YlAO','Hola a todos! Me registré en la encuesta!','rata'),
VALUES('buscossugar69','buscossugar69@gmail.com','Anónimo','$2y$10$aSYXF8U8K23gtLqtesHKwOzQB72yv58RJhZ02ApwtXgN3FAG2YlAO','Hola a todos! Me registré en la encuesta!','buscossugar69'),
VALUES('richgm13','richgm13@gmail.com','Anónimo','$2y$10$aSYXF8U8K23gtLqtesHKwOzQB72yv58RJhZ02ApwtXgN3FAG2YlAO','Hola a todos! Me registré en la encuesta!','richgm13'),
VALUES('bartgamer','bartgamer@gmail.com','Anónimo','$2y$10$aSYXF8U8K23gtLqtesHKwOzQB72yv58RJhZ02ApwtXgN3FAG2YlAO','Hola a todos! Me registré en la encuesta!','bartgamer'),
VALUES('santigameplays','santigameplays@gmail.com','Anónimo','$2y$10$aSYXF8U8K23gtLqtesHKwOzQB72yv58RJhZ02ApwtXgN3FAG2YlAO','Hola a todos! Me registré en la encuesta!','santigameplays'),
VALUES('puppycornio rosa','puppycornio rosa@gmail.com','Anónimo','$2y$10$aSYXF8U8K23gtLqtesHKwOzQB72yv58RJhZ02ApwtXgN3FAG2YlAO','Hola a todos! Me registré en la encuesta!','puppycornio rosa'),
VALUES('currito55','currito55@gmail.com','Anónimo','$2y$10$aSYXF8U8K23gtLqtesHKwOzQB72yv58RJhZ02ApwtXgN3FAG2YlAO','Hola a todos! Me registré en la encuesta!','currito55'),
VALUES('unrealteacher','unrealteacher@gmail.com','Anónimo','$2y$10$aSYXF8U8K23gtLqtesHKwOzQB72yv58RJhZ02ApwtXgN3FAG2YlAO','Hola a todos! Me registré en la encuesta!','unrealteacher'),
VALUES('yordikings','yordikings@gmail.com','Anónimo','$2y$10$aSYXF8U8K23gtLqtesHKwOzQB72yv58RJhZ02ApwtXgN3FAG2YlAO','Hola a todos! Me registré en la encuesta!','yordikings'),
VALUES('tumba burras','tumba burras@gmail.com','Anónimo','$2y$10$aSYXF8U8K23gtLqtesHKwOzQB72yv58RJhZ02ApwtXgN3FAG2YlAO','Hola a todos! Me registré en la encuesta!','tumba burras'),
VALUES('penesaurio','penesaurio@gmail.com','Anónimo','$2y$10$aSYXF8U8K23gtLqtesHKwOzQB72yv58RJhZ02ApwtXgN3FAG2YlAO','Hola a todos! Me registré en la encuesta!','penesaurio'),
VALUES('xxfoexxenemyxx','xxfoexxenemyxx@gmail.com','Anónimo','$2y$10$aSYXF8U8K23gtLqtesHKwOzQB72yv58RJhZ02ApwtXgN3FAG2YlAO','Hola a todos! Me registré en la encuesta!','xxfoexxenemyxx'),
VALUES('eltirijillo','eltirijillo@gmail.com','Anónimo','$2y$10$aSYXF8U8K23gtLqtesHKwOzQB72yv58RJhZ02ApwtXgN3FAG2YlAO','Hola a todos! Me registré en la encuesta!','eltirijillo'),
VALUES('humbertoibn','humbertoibn@gmail.com','Anónimo','$2y$10$aSYXF8U8K23gtLqtesHKwOzQB72yv58RJhZ02ApwtXgN3FAG2YlAO','Hola a todos! Me registré en la encuesta!','humbertoibn'),
VALUES('calleja098','calleja098@gmail.com','Anónimo','$2y$10$aSYXF8U8K23gtLqtesHKwOzQB72yv58RJhZ02ApwtXgN3FAG2YlAO','Hola a todos! Me registré en la encuesta!','calleja098');